### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by MKCarter** [Merck/BioPhi-2021-publication#1]
Hey, 

I might be missing something obvious here, but some of the files needed for running the jupyter notebooks are not included in this repo. For example, in the notebook - 02_cdr_grafting_25_pairs.ipynb

`FileNotFoundError: [Errno 2] No such file or directory: '../../work/TheraSAbDab_Germlines_Included.csv'`

There appear to be several references to the work folder, I wonder if this data is included in this repo?

Thanks,
Mike

**Comment by prihoda** [comment]
Hi @MKCarter thanks for the heads up. Indeed the `work` folder was not included on purpose. It mostly hosts big files like the OASis database (which can be downloaded from Zenodo https://zenodo.org/record/5164685).

Not sure why the TheraSAbDab file was in the `work` folder. I don't have access to the particular file anymore, but you can actually skip that part of the analysis, since it was only used to get the counts of the most common heavy-light germline pairs. I will comment out that part in the notebook.

Are there any other files missing?

**Comment by MKCarter** [comment]
Hey @prihoda,
Thanks for letting me know. Yeah, I downloaded the OASIS db and can confirm the code works as expected. 
All the best,
Mike
